### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Entrpix**
I was told too :3 
image

### CODE REVIEW

**Comment by Entrpix** [comment]
updated

**Review by FoxMoss — APPROVED** [review]

**Comment by Entrpix** [comment]
WOOOOOOO

**Review by Percslol — APPROVED** [review]

**Review by Percslol — APPROVED** [review]

**Comment by Entrpix** [comment]
YEAHHHHH

**Comment by MadjikDotPng** [comment]
I hate you all

**Comment by Entrpix** [comment]
WHY

**Comment by AverageJuliet** [comment]
lore

**Comment by MadjikDotPng** [comment]
what is the point, seriously, i dont like the taunting, i miss you all but if you're going to do this fuck off

**Comment by MadjikDotPng** [comment]
image
thanks for this btw

**Pull request closed without merging**
