### PR TITLE
You are no longer a member of any of the groups listed.

### PR DESCRIPTION
**Pull request by 5VER5GEUN1X**
this is impersonation.

### CODE REVIEW

**Comment by AverageJuliet** [comment]
further more, i am merely a messenger, i do not know why these people think you are a pedo but i was told to ban you from nebula on sight.

**Comment by MadjikDotPng** [comment]
who are these people

**Comment by MadjikDotPng** [comment]
also riftriot says he needs me for nebula possibly if i cared to help

**Comment by MadjikDotPng** [comment]
and my mw ban lasts for another 1-2 months, or indefinitely depending on my outcome

**Comment by MadjikDotPng** [comment]
so fuck off asshole, thanks for helping the wrong people

**Comment by AverageJuliet** [comment]
you have a pedo on your friendslist, you cannot be talking rn 
image

**Comment by AverageJuliet** [comment]
> and my mw ban lasts for another 1-2 months, or indefinitely depending on my outcome

image

**Comment by AverageJuliet** [comment]
> also riftriot says he needs me for nebula possibly if i cared to help

image

**Comment by AverageJuliet** [comment]
furthermore, you are such a fucking liar lol, your apologies are nothing but bullshit and everyone knows this, i was never drunk i just wanted to get rid of you.

**Comment by AverageJuliet** [comment]
now please accept this PR, its not right to state you are in groups you are now banned from.

**Comment by MadjikDotPng** [comment]
your arguments are all shit.

i thought you were cool you sick autistic fuck

**Comment by MadjikDotPng** [comment]
none of you gave me a damn chance to move on

**Comment by MadjikDotPng** [comment]
you cant call me a fucking pedo

i have a fucking boyfriend now
would someone like him wanna date a fucking pedophile??

**Comment by MadjikDotPng** [comment]
You ripped my last fucking hobby right out of my fucking hands, and for what, something i did almost a month or so ago, which has been resolved with both people affected? Both whom have forgiven me???

**Comment by MadjikDotPng** [comment]
the only reason rift isnt letting me in nebula rn is because he doesnt want your dumbass causing more drama

**Comment by MadjikDotPng** [comment]
there, i changed it!!1 are you fucking happy now?? you and your sick friends determined to fuck me over??? i have fucking nothing!!1

**Comment by MadjikDotPng** [comment]
> > and my mw ban lasts for another 1-2 months, or indefinitely depending on my outcome
> 
> image

im quoting rafflesia herself

**Comment by MadjikDotPng** [comment]
we talk in the damn gc with not only her but the damn pedo victim whomst forgives me and i talk to daily

**Comment by thonkinator** [comment]
i mean i can check with them but given the way they talk about you it seems the pedo victim has not forgiven you

**Comment by AverageJuliet** [comment]
> your arguments are all shit.
> 
> i thought you were cool you sick autistic fuck

what does autism have to do with this

**Comment by AverageJuliet** [comment]
> foxx is a fucking pedo, why would i associate with a fucking pedophile? im fucking 15 i dont wanna be fucking molested

then why did you have him friended? why did i hear about him DMing you? i wonder...

**Comment by AverageJuliet** [comment]
> there, i changed it!!1 are you fucking happy now?? you and your sick friends determined to fuck me over??? i have fucking nothing!!1

you have nothing? there's more to life outside of proxy servers and github commits

**Comment by AverageJuliet** [comment]
> the only reason rift isnt letting me in nebula rn is because he doesnt want your dumbass causing more drama

rift never stopped you.

**Comment by AverageJuliet** [comment]
now since you finally listened, im closing this PR. have fun.

**Comment by wearrrrr** [comment]
> none of you gave me a damn chance to move on

if you want to move on then how about you remove the old shit from your profile??? That's all we are asking, I don't care what you do after that but we just don't want you linked to our name anymore.

**Comment by MadjikDotPng** [comment]
> > foxx is a fucking pedo, why would i associate with a fucking pedophile? im fucking 15 i dont wanna be fucking molested
> 
> then why did you have him friended? why did i hear about him DMing you? i wonder...

i cant find him cuz i removed him, i cant find his profile

**Comment by MadjikDotPng** [comment]
all i need is one question answered:

why now do you guys snap
despite nothing even happening for the past month and a half

**Comment by thonkinator** [comment]
> all i need is one question answered:
> 
> why now do you guys snap despite nothing even happening for the past month and a half

i think juliet made this pull because of the interstellar ban

**Comment by thonkinator** [comment]
i think it would be best for everyone if this was abandoned and/or locked
(juliet will not leave it alone

**Comment by Entrpix** [comment]
Lore

**Comment by MadjikDotPng** [comment]
I hate you all. Besides the victim herself. She's the only one who understands jack shit.

**Comment by MadjikDotPng** [comment]
It's not fair that you guys only listen to the shit people tell you I totally did totally like wtf you aren't even going to ask me? Like tf am I going to do? Lie? Its too fucking late for lying.

**Comment by MadjikDotPng** [comment]
> > none of you gave me a damn chance to move on
> 
> if you want to move on then how about you remove the old shit from your profile??? That's all we are asking, I don't care what you do after that but we just don't want you linked to our name anymore.

There isn't shit you can do fucker. I always will be linked to all of those groups by my contributions.

**Comment by CoolElectronics** [comment]
you have contributed absolutely nothing of meaning to a single mercury project. your 3 lines of css on anura were rolled back months ago anyway

**Comment by MadjikDotPng** [comment]
> you have contributed absolutely nothing of meaning to a single mercury project. your 3 lines of css on anura were rolled back months ago anyway

this was lowk a lie lol i still have a lot of my work reflected back in modern anura, including the whole logo

**Comment by MadjikDotPng** [comment]
this whole thread was so stupid

**Comment by ProgrammerIn-wonderland** [comment]
The anura logo was made by rabbithawk

**Comment by ProgrammerIn-wonderland** [comment]
And I mean I've git blamed, there are seriously only 12 lines still attributed to you in AnuraOS, v2.0 was almost a full rewrite

**Comment by BomberFish** [comment]
certified loverboy certified pedophile wop wop wop wop wop

**Comment by BomberFish** [comment]
\+ anura 2.0 >>>> high diff

**Comment by velzie** [comment]
why did you bring this up again
you don't care for us, we don't care for you, end of story just drop it

**Comment by MadjikDotPng** [comment]
> The anura logo was made by rabbithawk

I am pretty confident I made the logo in photopea during school and rabbit made it better and svg? I honestly could be wrong here, it's been over a year.

**Comment by MadjikDotPng** [comment]
> why did you bring this up again you don't care for us, we don't care for you, end of story just drop it

I'm not bringing up old shit, I was bored in nebula and decided to look through this thread for laughs.

**Comment by MadjikDotPng** [comment]
Laughs at myself of course, I wasn't expecting a response?

**Comment by velzie** [comment]
but you replied saying we were wrong. that's kind of bringing up old shit. anyway this is a year old no one still gaf

**Comment by MadjikDotPng** [comment]
I legit had no clue anyone would see this...

**Comment by MadjikDotPng** [comment]
Also I didn't mean my actual code, I just meant my work wayyyyyyy early into the development being a building block to what it is now.. pretty much everything I did for anura has been rewritten or removed.

**Comment by MadjikDotPng** [comment]
> certified loverboy certified pedophile wop wop wop wop wop

Hiiii bomber have I talked to you since I got back?

**Pull request closed without merging**
